name: grumetsearch
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#追加
  http: ^1.1.0 #APIリクエスト用
  flutter_dotenv: ^5.1.0 # APIキーを隠す用

  flutter_launcher_icons: ^0.13.1 #アプリのアイコンを変える

  geocoding: ^3.0.0 #現在位置のより詳細
  geolocator: ^11.0.0 #現在位置を取得する

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

    #追加
  http: ^1.1.0 #APIリクエスト用
  flutter_dotenv: ^5.1.0 # APIキーを隠す用

  flutter_launcher_icons: ^0.13.1 #アプリのアイコンを変える

  geocoding: ^3.0.0 #現在位置のより詳細
  geolocator: ^11.0.0 #現在位置を取得する

  flutter_lints: ^2.0.0
flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - .env


